server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=source,xiushi
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
              - Path=/api/**
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=xiushi, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: xiushi-fallback
#          uri: https://www.yuque.com
#          predicates:
#              - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
