server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=source,xiushi
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
              - Path=/api/**
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=xiushi, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: xiushi-fallback
#          uri: https://www.yuque.com
#          predicates:
#              - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-provider
#    qos-port: 33333
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: -1
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848
